version: '3.1'

services:
  mongo:
    image: mongo
    container_name: stream-app-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: video_stream
    volumes:
#      for docker on window
#      - mongodb-storage:/data/db
#      for docker on ubuntu
      - ./docker/mongodb:/data/db
      - ./docker/mongo-config:/data/configdb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: stream-app-mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
#
#volumes:
#  mongodb-storage:
#    driver: local