app:
  videos:
    location: videos
  extensions:
    video: mp4
    subtitle: vtt
server:
  port: 8082
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: example
      port: 27017
      host: localhost
      database: video_stream